# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('division_name', models.CharField(max_length=255)),
                ('region_name', models.CharField(max_length=255)),
                ('circle_name', models.CharField(max_length=255)),
                ('taluk', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the office', max_length=255)),
                ('type', models.CharField(choices=[('B.O', 'Branch post office'), ('H.O', 'Head post office'), ('S.O', 'Sub post office')], help_text='Type of the office', max_length=3)),
                ('delivery_status', models.CharField(choices=[('Delivery', 'Delivery'), ('Non-Delivery', 'Non Delivery')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin_search.Location')),
                ('office', models.ForeignKey(help_text='associated office object', on_delete=django.db.models.deletion.CASCADE, to='pin_search.Office')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='officelocation',
            unique_together=set([('location', 'office')]),
        ),
    ]
